variable "lambda_name" {
  type        = string
  description = "Name of the lambda function"
}

variable "lambda_role_name" {
  type        = string
  description = "Name of the lambda IAM role"
}


variable "sns_topic_names" {
  type        = list(string)
  description = "Names of the SNS topics"
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to the resources generated by this module"
  default     = {}

}

variable "account_id" {
  type        = string
  description = "AWS account ID"
}

variable "region" {
  type        = string
  description = "AWS region"
}

locals {
  tags = merge(var.tags, {
    "Source" = "Terraform"
    "Module" = "lambda-sns-permissions"
  })
  sns_topic_arns_with_name = [for name in var.sns_topic_names : "arn:aws:sns:${var.region}:${var.account_id}:${name}"]
}
